background {
    monitor =
    path = /home/alessandro/Pictures/wallpaper.png
    blur_passes = 3
    blur_size = 8
    brightness = 0.5
}

# time
label {
    monitor =
    text = $TIME
    color = rgba(200, 200, 200, 1.0)
    font_size = 80
    font_family = SF Pro Display Bold
    position = 0, 150
    halign = center
    valign = center
}

# date
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    color = rgba(200, 200, 200, 0.7)
    font_size = 20
    font_family = SF Pro Display Bold
    position = 0, 60
    halign = center
    valign = center
}

# password field
input-field {
    monitor =
    size = 250, 40
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.2
    inner_color = rgba(0, 0, 0, 0.5)
    font_color = rgba(200, 200, 200, 1.0)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    position = 0, -50
    halign = center
    valign = center
}

